name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","refactor","ci","perf","chore","revert"]'
          add_scope_label: 'true'
          custom_labels: '{"feat": "feature", "fix": "fix", "docs": "documentation", "test": "test", "refactor": "refactor", "ci": "CI/CD", "perf": "performance", "chore": "chore", "revert": "revert"}'
